apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: public-net
  namespace: openshift-storage
  labels: {}
  annotations: {}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br-ex",
      "mode": "bridge",
      "ipam": {
            "type": "whereabouts",
            "range": "fd01:db8:1:1::/96",
            "routes": [{"dst": "fd01:db8:3:1::/96"}]
      }
  }'
