apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ceph-public-net-shim-worker-node
  namespace: openshift-storage
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    kubernetes.io/hostname: worker-node
  desiredState:
    interfaces:
      - name: odf-pub-shim
        description: Shim interface used to connect host to OpenShift Data Foundation public Multus network
        type: mac-vlan
        state: up
        mac-vlan:
          base-iface: enp1s0f1
          mode: bridge
          promiscuous: true
        ipv6:
          enabled: true
          dhcp: false
          address:
            - ip: fd01:db8:3:1::1 # STATIC IP FOR worker node
              prefix-length: 96
    routes:
      config:
        - destination: fd01:db8:1:1::/96
          next-hop-interface: odf-pub-shim
        - destination: fd01:db8:2:1::/96
          next-hop-interface: odf-pub-shim
